using System.Globalization;
using System.IO;
using System.Text;
using SwitchCfwWizard.Infrastructure;
using SwitchCfwWizard.Models;

namespace SwitchCfwWizard.Services;

public sealed class ConfigGenerationResult
{
    /// <summary>
    /// 本次在 out/ 里写出的**全部**文件：配置文件 + payload + 合并进来的组件本体。
    /// 清单、清理旧文件、打包校验都用它，所以合并进来的组件文件也必须记进来——
    /// 漏记会导致换组件/换版本后旧文件永远清不掉，被一起拷进 SD 卡。
    /// </summary>
    public List<string> WrittenFiles { get; } = new();

    /// <summary>其中由配置生成器写出的配置文件（ini / hosts），不含组件本体和 payload。</summary>
    public List<string> ConfigFiles { get; } = new();

    public int MergedFileCount { get; set; }

    /// <summary>
    /// 每个被勾选的组件**各自**合并进 <c>out/</c> 的文件数。
    ///
    /// 为什么要按组件分开记：<see cref="MergedFileCount"/> 是**总数**，而总数证明不了完整性。
    /// 勾了四个组件、其中一个一个文件都没合进来（解压目录缺失 / 解压中途失败），
    /// 只要另外三个合进来几十个文件，总数照样大于 0 —— 体检报告会写着「已合并 N 个组件文件」，
    /// 而用户拷进 SD 卡的是一份「看着生成成功、实际缺了一个组件」的产物。
    /// 这正是「计数断言不是完整性断言」在**运行期校验器**里的翻版。
    ///
    /// 键包含合并数为 0 的被勾选组件（命中即代表「勾了」），没勾的组件不入表。
    /// </summary>
    public Dictionary<ComponentKind, int> MergedFilesByComponent { get; } = new();

    /// <summary>
    /// 放进 <c>out/</c> 的 payload 文件（相对路径，统一用 <c>/</c> 分隔）。
    /// 例如 <c>bootloader/payloads/fusee.bin</c>、<c>payload.bin</c>、<c>bootloader/update.bin</c>。
    /// </summary>
    public List<string> PayloadFiles { get; } = new();

    /// <summary>记录一个由配置生成器写出的配置文件。</summary>
    public void AddConfigFile(string relativePath)
    {
        AddProducedFile(relativePath);
        ConfigFiles.Add(relativePath);
    }

    /// <summary>
    /// 记录一个产出文件（payload / 组件本体）。同一路径只记一次——
    /// Hekate 的 zip 里就带着 <c>hekate_ctcaer_*.bin</c>，合并和 payload 复制会先后碰到它。
    /// </summary>
    public void AddProducedFile(string relativePath)
    {
        if (!WrittenFiles.Contains(relativePath, StringComparer.OrdinalIgnoreCase))
        {
            WrittenFiles.Add(relativePath);
        }
    }
}

/// <summary>
/// 根据用户勾选项生成 out 目录下的全部配置文件。
/// </summary>
public sealed class ConfigGenerator
{
    private const string ManifestFileName = ".wizard-manifest.json";

    /// <summary>内置的 SX GEAR 引导文件，写到 out 根目录时用的文件名。</summary>
    private const string BootDatFileName = "boot.dat";

    private readonly ILogSink _log;

    public ConfigGenerator(ILogSink log) => _log = log;

    public ConfigGenerationResult Generate(WizardOptions options, CancellationToken cancellationToken)
    {
        var result = new ConfigGenerationResult();
        var outRoot = AppPaths.OutputRoot;
        AppPaths.EnsureDirectory(outRoot);

        CleanPreviousOutput(outRoot, result);

        var stamp = DateTimeOffset.Now.ToString("yyyy-MM-dd HH:mm:ss zzz", CultureInfo.InvariantCulture);
        var header = $"由 Switch CFW 配置向导生成 / Generated by Switch CFW Wizard · {stamp}";

        // 0) 可选：先把解压好的组件文件合并进 out
        //
        // 必须排在配置生成**之前**：组件包里可能带着同名文件（比如 Ultrahand 的
        // sdout.zip 里有 config/ultrahand/config.ini、hekate 早期版本的包里带
        // bootloader/hekate_ipl.ini）。后写的赢，所以让「我们生成的配置」压过
        // 「组件包里的示例配置」，否则用户在界面上选的引导项会被悄悄冲掉。
        if (options.IncludeComponentFilesInOutput)
        {
            result.MergedFileCount = MergeComponentFiles(options, outRoot, result, cancellationToken);
            if (result.MergedFileCount > 0)
            {
                _log.Info(string.Format(
                    Localization.LocalizationService.Instance["Log.Merged"],
                    result.MergedFileCount));
            }
        }

        // 1) Atmosphere 相关配置
        if (options.Atmosphere)
        {
            WriteAtmosphereConfigs(options, outRoot, header, result, cancellationToken);

            // 两个 90DNS 开关各管一个系统，且都要求对应的引导模式勾着（与 blank_prodinfo_* 同一套规矩）：
            // 复选框本身就是「只在勾了那个引导模式时才显示」，隐藏状态下存档里可能仍是 true，
            // 所以这里再与引导模式与一次，避免出现「界面上看不见、产物里却多了一份屏蔽表」。
            if ((options.Use90DnsSysmmc && options.BootSysNand)
                || (options.Use90DnsEmummc && options.BootEmuNand))
            {
                WriteHostsFiles(options, outRoot, result, cancellationToken);
            }
        }
        else if (options.Use90DnsSysmmc || options.Use90DnsEmummc
                 || options.BlankSerialSysmmc || options.BlankSerialEmummc || options.Ram8Gb)
        {
            _log.Warn("未勾选 Atmosphere，屏蔽序列号 / 90DNS / exosphere 相关配置不会被写入。");
        }

        // 2) Hekate 相关配置
        if (options.Hekate)
        {
            WriteHekateConfigs(options, outRoot, header, result, cancellationToken);
        }
        else if (options.HasAnyBootEntry)
        {
            _log.Warn("未勾选 Hekate，引导项（hekate_ipl.ini）不会被写入。");
        }

        // 3) Sys-patch 配置
        if (options.SysPatch)
        {
            WriteSysPatchConfig(options, outRoot, header, result, cancellationToken);
        }

        // 4) Ultrahand 配置
        if (options.Ultrahand)
        {
            WriteUltrahandConfig(options, outRoot, header, result, cancellationToken);
        }

        // 5) 可选：把 payload 放到它该在的位置
        //
        // 必须排在**组件合并之后**：hekate 的包里自带一份 bootloader/update.bin（标准 4G 版），
        // 而用户在界面上选的可能是 8G 版 payload。后写的赢，所以让「选中的 payload」压过
        // 「包里的那份」，否则界面显示 8G、机器实际按 4G 起，而且完全静默。
        if (options.IncludePayloads)
        {
            MergePayloads(options, outRoot, result, cancellationToken);
        }

        // 5.5) payload.bin 兜底
        //
        // 有些源不发独立的 .bin 资源（hekate 的中文本地化仓库就是这样，payload 只在包里），
        // 于是「散装 payload 摆放」这一步无货可摆。但 hekate 的约定名是根目录 payload.bin，
        // 而包里的那份叫 hekate_ctcaer_<ver>.bin —— 不补这一步，用户会看到
        // 「只是换了个界面语言，payload.bin 就不见了」。
        EnsureRootPayloadBin(options, outRoot, result, cancellationToken);

        // 6) 8G 运存模式下清掉 out 根目录里的标准版（4G）hekate payload
        RemoveStandardHekatePayloadFromRoot(options, outRoot, result);

        // 7) 可选：把下载好的 boot.dat 复制到 out 根目录
        if (options.IncludeBootDat)
        {
            WriteBootDat(options, outRoot, result);
        }

        WriteManifest(outRoot, result);
        return result;
    }

    /// <summary>
    /// 保证 <c>out/payload.bin</c> 存在：不存在时，从组件包自带的根目录
    /// <c>hekate_ctcaer_&lt;ver&gt;.bin</c> 复制一份过去。
    ///
    /// 为什么需要它：hekate 的中文本地化仓库（<c>easyworld/hekate</c>）只发 zip，不发独立的
    /// <c>.bin</c> 资源，所以「把 payload 放到对应目录」那一步无货可摆 —— 而包里的 payload
    /// 叫 <c>hekate_ctcaer_&lt;ver&gt;.bin</c>，不是 hekate 约定的 <c>payload.bin</c>。
    /// 不补这一步，用户会以为「换个语言把 payload 弄丢了」。
    ///
    /// **只在「恰好一个」候选时动手**：多个候选说明情况不明（比如用户自己往 out 里塞过东西），
    /// 与其猜一个，不如什么都不做 —— 猜错的代价是把一个错的 payload 当成启动项。
    /// 已经存在 <c>payload.bin</c> 时（官方源 / 8G 模式）直接返回，绝不覆盖。
    /// </summary>
    private void EnsureRootPayloadBin(
        WizardOptions options,
        string outRoot,
        ConfigGenerationResult result,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (!options.Hekate || !options.IncludePayloads || !Directory.Exists(outRoot))
        {
            return;
        }

        var target = Path.Combine(outRoot, "payload.bin");
        if (File.Exists(target))
        {
            return;
        }

        var candidates = Directory
            .EnumerateFiles(outRoot, "hekate_ctcaer_*.bin")
            // 8G 版 payload 不能当「标准版」的补位 —— 判据走 ComponentCatalog.IsRam8GbPayloadName，
            // 别在这里再写一份 ram8GB 字面量（上游改命名规则时会与 picker 悄悄脱节）。
            .Where(f => !ComponentCatalog.IsRam8GbPayloadName(Path.GetFileName(f)))
            .ToList();

        if (candidates.Count != 1)
        {
            return;
        }

        var source = candidates[0];
        try
        {
            File.Copy(source, target, overwrite: true);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            _log.Warn(string.Format(
                Localization.LocalizationService.Instance["Log.PayloadBinFallbackFailed"],
                Path.GetFileName(source),
                ex.Message));
            return;
        }

        result.AddProducedFile("payload.bin");
        _log.Info(string.Format(
            Localization.LocalizationService.Instance["Log.PayloadBinFallback"],
            Path.GetFileName(source)));
    }

    /// <summary>
    /// 8G 运存模式下，把 <c>out/</c> 根目录里的标准版（4G）hekate payload 删掉。
    ///
    /// 这个文件不是我们放进去的，而是 hekate 组件包**自带**的：Nyx 包里同时有
    /// <c>bootloader/update.bin</c> 和根目录的 <c>hekate_ctcaer_&lt;ver&gt;.bin</c>，
    /// 整棵铺开后就落在了 out 根目录。既然已经按 8G 版放好了 <c>payload.bin</c> /
    /// <c>bootloader/update.bin</c>，根目录再留一个 4G 版的同名文件，只会让人分不清
    /// 机器到底按哪个起 —— 而且名字一模一样，肉眼极难发现版本不对。
    ///
    /// 标准版本身**仍然保留**在 <c>bootloader/payloads/</c> 里，可在 hekate 的 payload
    /// 菜单中直接选中启动，所以「随时切回 4G」的能力没有丢。
    ///
    /// 只认根目录、只认 <c>hekate_ctcaer_*.bin</c> 且名字里不含 <c>ram8GB</c> 的文件，
    /// 绝不动其它东西。判据是 <see cref="ComponentCatalog.IsRam8GbPayloadName"/>（与 picker 共用同一份）。
    /// </summary>
    private void RemoveStandardHekatePayloadFromRoot(
        WizardOptions options,
        string outRoot,
        ConfigGenerationResult result)
    {
        if (!options.Ram8Gb || !options.Hekate || !Directory.Exists(outRoot))
        {
            return;
        }

        foreach (var file in Directory.EnumerateFiles(outRoot, "hekate_ctcaer_*.bin"))
        {
            var name = Path.GetFileName(file);
            // 判据同上：8G 版 payload 是**要留的**那一个，认错了会把它一起删掉。
            if (ComponentCatalog.IsRam8GbPayloadName(name))
            {
                continue;
            }

            try
            {
                File.Delete(file);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                _log.Warn(string.Format(
                    Localization.LocalizationService.Instance["Log.StandardPayloadRemoveFailed"],
                    name,
                    ex.Message));
                continue;
            }

            // 清单里也要抹掉：它在合并阶段已经被记进去了，留着的话打包校验会报
            // 「清单中的文件不在包内」这种自相矛盾的结论。
            result.WrittenFiles.RemoveAll(path => string.Equals(path, name, StringComparison.OrdinalIgnoreCase));

            _log.Info(string.Format(
                Localization.LocalizationService.Instance["Log.StandardPayloadRemoved"],
                name));
        }
    }

    /// <summary>
    /// 把随程序内置的 <c>boot.dat</c> 写到 <c>out/</c> 根目录。
    ///
    /// 必须用 <see cref="File.WriteAllBytes"/>：走 <see cref="WriteFile"/> 会被当成文本做
    /// CRLF 归一化，二进制内容当场损坏（而且日志上一点异常都看不出来）。
    /// </summary>
    /// <summary>
    /// 把**已下载的** <c>boot.dat</c> 复制到 <c>out/</c> 根目录。
    ///
    /// 这个文件自 2026-09-21 起不再内嵌在程序里：下载阶段按高级设置里的地址取回来，
    /// 路径经 <see cref="WizardOptions.BootDatPath"/> 带到这里（见 <see cref="BootDatSource"/>）。
    ///
    /// 拿不到就**警告并跳过**、不中止整轮 —— 它只是「输出内容」里的一个可选文件，
    /// 为它把其余组件的产物一起放弃，代价明显不对等。
    /// 但日志里要写清**是哪一种拿不到**（地址没解析出来 / 下载失败 / 没勾），
    /// 否则用户只看到「out 里少了 boot.dat」，不知道该去改哪一处。
    /// </summary>
    private void WriteBootDat(WizardOptions options, string outRoot, ConfigGenerationResult result)
    {
        var source = options.BootDatPath;

        if (string.IsNullOrWhiteSpace(source) || !File.Exists(source))
        {
            _log.Warn(Localization.LocalizationService.Instance["Log.BootDatMissing"]);
            return;
        }

        AppPaths.EnsureDirectory(outRoot);
        File.Copy(source, Path.Combine(outRoot, BootDatFileName), overwrite: true);

        // 进清单（但不进 ConfigFiles：它不是 ini/hosts，不该算进「配置文件齐全，共 N 个」）
        result.AddProducedFile(BootDatFileName);

        _log.Info(string.Format(
            Localization.LocalizationService.Instance["Log.BootDatWritten"],
            BootDatFileName));
    }

    // ── Atmosphere ──────────────────────────────────────────────
    private void WriteAtmosphereConfigs(
        WizardOptions options,
        string outRoot,
        string header,
        ConfigGenerationResult result,
        CancellationToken cancellationToken)
    {
        var definition = ComponentCatalog.Get(ComponentKind.Atmosphere);

        // exosphere.ini
        var exosphere = new IniDocument();
        exosphere.HeaderComment("; " + header);
        exosphere.HeaderComment("; 参考：https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/features/configurations.md");

        exosphere.Set("exosphere", "debugmode", "1");
        exosphere.Comment("exosphere", "用户态调试模式（0 = 关闭）");
        exosphere.Set("exosphere", "debugmode_user", Option(options, definition, "debugmode_user"));
        exosphere.Comment("exosphere", "禁用用户异常处理（0 = 保持启用）");
        exosphere.Set("exosphere", "disable_user_exception_handlers", Option(options, definition, "disable_user_exception_handlers"));
        exosphere.Comment("exosphere", "允许用户态访问 PMU（0 = 禁止）");
        exosphere.Set("exosphere", "enable_user_pmu_access", Option(options, definition, "enable_user_pmu_access"));

        exosphere.Comment("exosphere", "8G 运存支持：零售机默认上限 4GB，开启后按物理容量自动选择（Hekate 引导项需同时设置 memmode=1）");
        exosphere.Set("exosphere", "enable_mem_mode", options.Ram8Gb ? "1" : "0");

        exosphere.Comment("exosphere", "屏蔽序列号：sysMMC（真实破解系统）");
        exosphere.Set("exosphere", "blank_prodinfo_sysmmc", options.BlankSerialSysmmc && options.BootSysNand ? "1" : "0");
        exosphere.Comment("exosphere", "屏蔽序列号：emuMMC（虚拟破解系统）");
        exosphere.Set("exosphere", "blank_prodinfo_emummc", options.BlankSerialEmummc && options.BootEmuNand ? "1" : "0");

        exosphere.Comment("exosphere", "是否允许在 sysMMC 中写入 PRODINFO（官方强烈不建议开启）");
        exosphere.Set("exosphere", "allow_writing_to_cal_sysmmc", Option(options, definition, "allow_writing_to_cal_sysmmc"));

        exosphere.Set("exosphere", "log_port", "0");
        exosphere.Set("exosphere", "log_baud_rate", "115200");
        exosphere.Set("exosphere", "log_inverted", "0");

        WriteFile(Path.Combine(outRoot, "exosphere.ini"), exosphere.Render(), result, cancellationToken);

        // atmosphere/config/system_settings.ini
        var settings = new IniDocument();
        settings.HeaderComment("; " + header);
        settings.HeaderComment("; 值格式为 <类型>!<值>，类型见 Atmosphere 文档：u8 / u64 / str");

        foreach (var option in definition.Options.Where(o =>
                     string.Equals(o.TargetFile, "atmosphere/config/system_settings.ini", StringComparison.OrdinalIgnoreCase)))
        {
            if (!string.IsNullOrEmpty(option.DescriptionKey))
            {
                settings.Comment(option.Section ?? "atmosphere",
                    Localization.LocalizationService.Instance[option.DescriptionKey]);
            }

            settings.Set(option.Section ?? "atmosphere", option.Key,
                FormatTypedValue(option.IniValuePrefix, Option(options, definition, option.Key)));
        }

        WriteFile(Path.Combine(outRoot, "atmosphere", "config", "system_settings.ini"), settings.Render(), result, cancellationToken);

        // atmosphere/config/stratosphere.ini
        var stratosphere = new IniDocument();
        stratosphere.HeaderComment("; " + header);
        var nogc = Option(options, definition, "nogc");
        if (nogc is "0" or "1")
        {
            stratosphere.Comment("stratosphere", "1 = 强制启用 nogc（始终禁用游戏卡读取器）；0 = 强制禁用");
            stratosphere.Set("stratosphere", "nogc", nogc);
        }
        else
        {
            stratosphere.Comment("stratosphere", "nogc 保持自动：由 Atmosphere 自行判断是否保护游戏卡读取器");
        }

        WriteFile(Path.Combine(outRoot, "atmosphere", "config", "stratosphere.ini"), stratosphere.Render(), result, cancellationToken);

        // atmosphere/config/override_config.ini
        //
        // [hbl_config] 告诉系统「Homebrew Menu 是哪个 title、怎么启动」，[default_config] 是
        // 用户平时按的两个组合键。两段的键名有重合（都有 override_key），但含义与取值都独立 ——
        // 在界面上它们的存储键因此各带前缀（hbl_*），写入时的键名由这里给出。
        var overrides = new IniDocument();
        overrides.HeaderComment("; " + header);
        overrides.Comment("hbl_config", "Homebrew Menu 的 title id 与启动方式");
        overrides.Set("hbl_config", "program_id", NormalizeTitleId(Option(options, definition, "hbl_program_id"), _log));
        overrides.Set("hbl_config", "override_any_app", Option(options, definition, "hbl_override_any_app"));
        overrides.Set("hbl_config", "path", NormalizeHblPath(Option(options, definition, "hbl_path"), _log));
        overrides.Set("hbl_config", "override_key", Option(options, definition, "hbl_override_key"));
        overrides.Set("hbl_config", "override_any_app_key", Option(options, definition, "hbl_override_any_app_key"));

        overrides.Comment("default_config", "启动游戏时按住该按键进入 Homebrew Menu（在按键前加 ! 可反转行为）");
        overrides.Set("default_config", "override_key", Option(options, definition, "override_key"));
        overrides.Comment("default_config", "按住该按键时启用金手指（在按键前加 ! 可反转行为）");
        overrides.Set("default_config", "cheat_enable_key", Option(options, definition, "cheat_enable_key"));
        WriteFile(Path.Combine(outRoot, "atmosphere", "config", "override_config.ini"), overrides.Render(), result, cancellationToken);
    }

    /// <summary>
    /// 校验 <c>[hbl_config] program_id</c>。
    ///
    /// 必须是**16 位十六进制**（title id 的固定宽度）。写进一份格式不对的值不会报错，
    /// 只会让 Homebrew Menu 在真机上永远起不来 —— 属于「看起来配了、其实没生效」，
    /// 所以这里回落到官方默认值并留一条警告，而不是原样写进去。
    /// </summary>
    private static string NormalizeTitleId(string? raw, ILogSink log)
    {
        var value = raw?.Trim() ?? string.Empty;
        if (value.Length == 16 && value.All(Uri.IsHexDigit))
        {
            return value.ToUpperInvariant();
        }

        if (!string.IsNullOrEmpty(value))
        {
            log.Warn($"hbl_config 的 program_id「{value}」不是 16 位十六进制，已改用官方默认值 {ComponentCatalog.HblProgramIdDefault}。");
        }

        return ComponentCatalog.HblProgramIdDefault;
    }

    /// <summary>
    /// 校验 <c>[hbl_config] path</c>：必须是 SD 卡内的**相对路径**。
    ///
    /// 绝对路径（含盘符或前导斜杠）与 <c>..</c> 都会被 Atmosphere 当成越界而拒绝加载，
    /// 后果同 <see cref="NormalizeTitleId"/>：文件看着没问题、菜单起不来。
    /// </summary>
    private static string NormalizeHblPath(string? raw, ILogSink log)
    {
        var value = (raw ?? string.Empty).Trim().Replace('\\', '/').TrimStart('/');
        var valid = !string.IsNullOrEmpty(value)
            && !value.Contains("..", StringComparison.Ordinal)
            && !value.Contains(':', StringComparison.Ordinal);

        if (valid)
        {
            return value;
        }

        if (!string.IsNullOrEmpty(value))
        {
            log.Warn($"hbl_config 的 path「{value}」不是 SD 卡内的相对路径，已改用官方默认值 {ComponentCatalog.HblPathDefault}。");
        }

        return ComponentCatalog.HblPathDefault;
    }

    private void WriteHostsFiles(
        WizardOptions options,
        string outRoot,
        ConfigGenerationResult result,
        CancellationToken cancellationToken)
    {
        var hostsRoot = Path.Combine(outRoot, "atmosphere", "hosts");
        var written = new List<string>();

        // 调用方已经保证「至少一个开关在对应引导模式下是开的」，所以这里可以放心写 default.txt。
        // 两个开关各自对应一份系统专属屏蔽表；default.txt 是两者共用的遥测屏蔽表。
        var wantSysmmc = options.Use90DnsSysmmc && options.BootSysNand;
        var wantEmummc = options.Use90DnsEmummc && options.BootEmuNand;

        // default.txt：任天堂遥测服务器（两个系统共用，只要有一个开关开着就写）
        var defaultHosts = new StringBuilder();
        defaultHosts.AppendLine("# Nintendo telemetry servers");
        defaultHosts.AppendLine("127.0.0.1 receive-%.dg.srv.nintendo.net receive-%.er.srv.nintendo.net");
        WriteFile(Path.Combine(hostsRoot, "default.txt"), defaultHosts.ToString(), result, cancellationToken);
        written.Add("default.txt");

        // sysmmc.txt：勾了「真实破解系统 90DNS」时写入
        if (wantSysmmc)
        {
            WriteFile(Path.Combine(hostsRoot, "sysmmc.txt"), NinetyDnsBlock, result, cancellationToken);
            written.Add("sysmmc.txt");
        }

        // emummc.txt：勾了「虚拟破解系统 90DNS」时写入
        if (wantEmummc)
        {
            WriteFile(Path.Combine(hostsRoot, "emummc.txt"), NinetyDnsBlock, result, cancellationToken);
            written.Add("emummc.txt");
        }

        _log.Info(string.Format(
            Localization.LocalizationService.Instance["Log.HostsWritten"],
            string.Join("、", written)));
    }

    // ── Hekate ──────────────────────────────────────────────────
    private void WriteHekateConfigs(
        WizardOptions options,
        string outRoot,
        string header,
        ConfigGenerationResult result,
        CancellationToken cancellationToken)
    {
        var definition = ComponentCatalog.Get(ComponentKind.Hekate);

        if (options.HasAnyBootEntry)
        {
            var ini = new IniDocument();
            ini.HeaderComment("; " + header);
            ini.HeaderComment("; 参考：https://github.com/CTCaer/hekate");

            // [config]
            foreach (var option in definition.Options.Where(o =>
                         string.Equals(o.TargetFile, "bootloader/hekate_ipl.ini", StringComparison.OrdinalIgnoreCase)))
            {
                ini.Set("config", option.Key, Option(options, definition, option.Key));
            }

            var entries = BuildBootEntries(options, definition, outRoot, result);
            var captioned = false;

            foreach (var entry in entries)
            {
                if (!captioned)
                {
                    ini.Caption(entry.Caption);
                    captioned = true;
                }

                ini.BootEntry(entry.Title, entry.Lines);
            }

            // autoboot 索引校验：超出范围则回退为 0
            var autobootRaw = Option(options, definition, "autoboot");
            if (int.TryParse(autobootRaw, out var index) && (index < 0 || index > entries.Count))
            {
                _log.Warn($"autoboot={index} 超出引导项范围（共 {entries.Count} 项），已回退为 0。");
                ini.OverrideKey("config", "autoboot", "0");
            }

            WriteFile(Path.Combine(outRoot, "bootloader", "hekate_ipl.ini"), ini.Render(), result, cancellationToken);
        }
        else
        {
            _log.Warn(Localization.LocalizationService.Instance["Log.NoBootEntry"]);
        }

        // nyx.ini
        var nyx = new IniDocument();
        nyx.HeaderComment("; " + header);
        foreach (var option in definition.Options.Where(o =>
                     string.Equals(o.TargetFile, "bootloader/nyx.ini", StringComparison.OrdinalIgnoreCase)))
        {
            nyx.Set("config", option.Key, Option(options, definition, option.Key));
        }

        WriteFile(Path.Combine(outRoot, "bootloader", "nyx.ini"), nyx.Render(), result, cancellationToken);
    }

    private List<BootEntry> BuildBootEntries(
        WizardOptions options,
        ComponentDefinition hekate,
        string outRoot,
        ConfigGenerationResult result)
    {
        var entries = new List<BootEntry>();

        var kip1Patch = options.GetBool(ComponentKind.Hekate, "kip1patch_nosigchk",
            hekate.Options.First(o => o.Key == "kip1patch_nosigchk").DefaultValue == "1");
        var kip1AtmosphereKips = options.GetBool(ComponentKind.Hekate, "kip1_atmosphere_kips");
        var usb3Force = options.GetBool(ComponentKind.Hekate, "usb3force");
        var noUserExceptions = options.GetBool(ComponentKind.Hekate, "nouserexceptions");
        var userPmu = options.GetBool(ComponentKind.Hekate, "userpmu");

        // 同一张图被两个引导项选中时，第二次复制会盖掉第一次，两个引导项就指向了同一张图。
        // 用这张表盯住「文件名 → 来源」，撞名时给后来者加前缀区分开。
        // 启动图（logopath）与图标（icon）**共用这一张表**：两者落在同一个 bootloader/res/ 目录里，
        // 撞名规则必须一致，否则「A 项的启动图」会盖掉「B 项的图标」。
        var stagedImages = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        void AddCommon(IList<string> lines)
        {
            // kip1 必须排在 pkg3 之后，hekate 会按顺序解析
            if (kip1AtmosphereKips)
            {
                lines.Add("kip1=atmosphere/kips/*");
            }

            if (kip1Patch)
            {
                lines.Add("kip1patch=nosigchk");
            }

            if (options.Ram8Gb)
            {
                lines.Add("memmode=1");
            }

            if (usb3Force)
            {
                lines.Add("usb3force=1");
            }

            if (noUserExceptions)
            {
                lines.Add("nouserexceptions=1");
            }

            if (userPmu)
            {
                lines.Add("userpmu=1");
            }
        }

        // 1) 正版系统
        if (options.BootStock)
        {
            var title = ComponentCatalog.ResolveBootTitle(options.BootStockTitle, "Boot.Entry.Stock");
            var lines = new List<string>
            {
                // 用 pkg3 而不是 fss0：两者功能完全相同（都从 package3 里提取
                // exosphere / warmboot / 核心 kips），但 hekate 官方 README 已把
                // fss0 标注为 !Deprecated!，所以新生成的配置一律用 pkg3。
                "pkg3=atmosphere/package3",
                "stock=1",
                "emummc_force_disable=1",
            };

            AppendBootImage(options.BootStockLogo, BootImageKind.Logo, "zsxt", title, lines, stagedImages, outRoot, result);
            AppendBootImage(options.BootStockIcon, BootImageKind.Icon, "zsxt", title, lines, stagedImages, outRoot, result);
            lines.Add("id=zsxt");

            entries.Add(new BootEntry(title, lines, "{------ Stock / OFW ------}"));
        }

        // 2) 真实破解系统（sysMMC）
        if (options.BootSysNand)
        {
            var title = ComponentCatalog.ResolveBootTitle(options.BootSysNandTitle, "Boot.Entry.SysNand");
            var lines = new List<string>
            {
                "pkg3=atmosphere/package3",
                "emummc_force_disable=1",
            };

            AddCommon(lines);

            // 屏蔽序列号时同步写 cal0blank：hekate 的**引导项参数会覆盖** exosphere.ini 的
            // blank_prodinfo_*。只改一边的话，会出现「exosphere 说屏蔽了、引导项又放开了」
            // 这种自相矛盾的组合，而且完全静默 —— 两处必须一致。
            if (options.BlankSerialSysmmc)
            {
                lines.Add("cal0blank=1");
            }

            AppendBootImage(options.BootSysNandLogo, BootImageKind.Logo, "zspjxt", title, lines, stagedImages, outRoot, result);
            AppendBootImage(options.BootSysNandIcon, BootImageKind.Icon, "zspjxt", title, lines, stagedImages, outRoot, result);
            lines.Add("id=zspjxt");

            entries.Add(new BootEntry(title, lines, "{------ Atmosphere ------}"));
        }

        // 3) 虚拟破解系统（emuMMC）
        if (options.BootEmuNand)
        {
            var title = ComponentCatalog.ResolveBootTitle(options.BootEmuNandTitle, "Boot.Entry.EmuNand");
            var lines = new List<string>
            {
                "pkg3=atmosphere/package3",
                "emummcforce=1",
            };

            AddCommon(lines);

            // 同 sysMMC：与 exosphere.ini 的 blank_prodinfo_emummc 保持一致
            if (options.BlankSerialEmummc)
            {
                lines.Add("cal0blank=1");
            }

            AppendBootImage(options.BootEmuNandLogo, BootImageKind.Logo, "xunipjx", title, lines, stagedImages, outRoot, result);
            AppendBootImage(options.BootEmuNandIcon, BootImageKind.Icon, "xunipjx", title, lines, stagedImages, outRoot, result);

            // id 上限是 7 个字符：hekate 内部按 char id[8] 存放，要留一个 NULL 终止符
            // （官方 README：id=IDNAME … Max 7 chars）。
            // 用户配置里写的 xunipjxt 是 8 个字符，实际生效的只有前 7 位，
            // 所以这里直接生成 7 字符版本，避免写进去一个「看起来对、其实被截断」的值。
            lines.Add("id=xunipjx");

            entries.Add(new BootEntry(title, lines, "{------ Atmosphere ------}"));
        }

        return entries;
    }

    /// <summary>
    /// 一个引导项上的「图片类」键。上游模板把 <c>logopath</c> 与 <c>icon</c> 归为同一族
    /// （原文："like logopath= key which is for bootlogo and icon= key for Nyx icon"），
    /// 两者除了键名与日志文案之外**行为完全一致**，所以共用一套复制/去重/登记逻辑。
    ///
    /// 分成两条路写（而不是复制一份方法）是刻意的：撞名去重那段逻辑很微妙（见
    /// <see cref="AppendBootImage"/>），复制一份必然会在某次改动后漂移。
    /// </summary>
    private readonly record struct BootImageKind(string IniKey, string MissingLogKey, string CopyFailedLogKey)
    {
        /// <summary><c>logopath</c>：进这一项时刷的启动图。</summary>
        public static readonly BootImageKind Logo = new("logopath", "Log.BootLogoMissing", "Log.BootLogoCopyFailed");

        /// <summary><c>icon</c>：这一项在 Nyx 菜单里显示的小图标。</summary>
        public static readonly BootImageKind Icon = new("icon", "Log.BootIconMissing", "Log.BootIconCopyFailed");
    }

    /// <summary>
    /// 把用户选的图片复制进 <c>out/bootloader/res/</c>，并把对应的键追加到该引导项。
    ///
    /// hekate 的 <c>logopath</c> / <c>icon</c> 都是**引导项级**的键，路径按 SD 卡根目录算，
    /// 所以写进去的必须是 <c>bootloader/res/&lt;文件名&gt;</c> 这种相对路径 ——
    /// 写绝对路径在机器上必然找不到图。
    ///
    /// 没填 / 文件已不在 / 复制失败都只是「这一项不设这张图」，不影响其它配置生成：
    /// 一张图缺失不该让整个流程失败（上游对两者都有回退链，缺失不是致命错误）。
    /// </summary>
    private void AppendBootImage(
        string? sourcePath,
        BootImageKind kind,
        string entryId,
        string entryLabel,
        IList<string> lines,
        Dictionary<string, string> staged,
        string outRoot,
        ConfigGenerationResult result)
    {
        if (string.IsNullOrWhiteSpace(sourcePath))
        {
            return;
        }

        var loc = Localization.LocalizationService.Instance;

        if (!File.Exists(sourcePath))
        {
            _log.Warn(string.Format(loc[kind.MissingLogKey], entryLabel, sourcePath));
            return;
        }

        var fileName = Path.GetFileName(sourcePath);
        if (string.IsNullOrWhiteSpace(fileName))
        {
            return;
        }

        // 两个引导项选了不同目录下的同名图：给后来者加该引导项的 id 前缀。
        // 不加的话后复制的那张会盖掉先复制的，两个引导项静默变成同一张图。
        if (staged.TryGetValue(fileName, out var owner)
            && !string.Equals(owner, sourcePath, StringComparison.OrdinalIgnoreCase))
        {
            fileName = entryId + "_" + fileName;
        }

        var targetDir = Path.Combine(outRoot, "bootloader", "res");
        var target = Path.Combine(targetDir, fileName);

        try
        {
            AppPaths.EnsureDirectory(targetDir);

            // 内容一样就不重写：少一次无意义的写盘，也让「这次没改动」在时间戳上看得见
            if (!File.Exists(target) || !FilesEqual(target, sourcePath))
            {
                File.Copy(sourcePath, target, overwrite: true);
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            _log.Warn(string.Format(loc[kind.CopyFailedLogKey], entryLabel, ex.Message));
            return;
        }

        staged[fileName] = sourcePath;
        result.AddProducedFile(Path.Combine("bootloader", "res", fileName));
        lines.Add(kind.IniKey + "=bootloader/res/" + fileName);
    }

    private static bool FilesEqual(string left, string right)
    {
        var a = new FileInfo(left);
        var b = new FileInfo(right);
        return a.Length == b.Length
            && File.ReadAllBytes(left).SequenceEqual(File.ReadAllBytes(right));
    }

    // ── Sys-patch ───────────────────────────────────────────────
    private void WriteSysPatchConfig(
        WizardOptions options,
        string outRoot,
        string header,
        ConfigGenerationResult result,
        CancellationToken cancellationToken)
    {
        var definition = ComponentCatalog.Get(ComponentKind.SysPatch);
        var ini = new IniDocument();
        ini.HeaderComment("; " + header);
        ini.HeaderComment("; 参考：https://github.com/impeeza/sys-patch");

        var userSysmmc = options.GetBool(ComponentKind.SysPatch, "patch_sysmmc", true);
        var userEmummc = options.GetBool(ComponentKind.SysPatch, "patch_emummc", true);

        ini.Comment("options", "勾选「真实破解系统」时该值才生效");
        ini.Set("options", "patch_sysmmc", options.BootSysNand && userSysmmc ? "1" : "0");

        ini.Comment("options", "勾选「虚拟破解系统」时该值才生效");
        ini.Set("options", "patch_emummc", options.BootEmuNand && userEmummc ? "1" : "0");

        foreach (var option in definition.Options.Where(o =>
                     o.Key is "enable_logging" or "version_skip"))
        {
            if (!string.IsNullOrEmpty(option.DescriptionKey))
            {
                ini.Comment("options", Localization.LocalizationService.Instance[option.DescriptionKey]);
            }

            ini.Set("options", option.Key, Option(options, definition, option.Key));
        }

        WriteFile(Path.Combine(outRoot, "config", "sys-patch", "config.ini"), ini.Render(), result, cancellationToken);
    }

    // ── Ultrahand ───────────────────────────────────────────────
    private void WriteUltrahandConfig(
        WizardOptions options,
        string outRoot,
        string header,
        ConfigGenerationResult result,
        CancellationToken cancellationToken)
    {
        var loc = Localization.LocalizationService.Instance;
        var definition = ComponentCatalog.Get(ComponentKind.Ultrahand);

        var raw = Option(options, definition, "key_combo");
        var combo = ComponentCatalog.NormalizeKeyCombo(raw);

        if (combo is null)
        {
            // settings.json 是可以手改的，组合键写坏了会让热键失效，这里兜回官方默认值
            _log.Warn(string.Format(loc["Log.InvalidKeyCombo"], raw, ComponentCatalog.DefaultKeyCombo));
            combo = ComponentCatalog.DefaultKeyCombo;
        }

        var ini = new IniDocument();
        ini.HeaderComment("; " + header);
        ini.HeaderComment("; 参考：https://github.com/ppkantorski/Ultrahand-Overlay");
        ini.Comment("ultrahand", "呼出 Ultrahand 的组合键（用 + 连接，2–4 个按键）");
        ini.Set("ultrahand", "key_combo", combo);

        // [ultrahand] default_lang —— Ultrahand 的界面语言。
        //
        // 上游拿它拼 config/ultrahand/lang/<代码>.json；文件不存在时该语言在 Ultrahand 自己的
        // 设置里会被**跳过**，于是「配置说中文、卡上没有中文包」会静默退回内置英文。
        // 这里只管一件事：写进去的**一定**是 14 个合法代码之一 —— 哨兵与损坏值都不许漏到 ini。
        // 「指向的语言包到底在不在产物里」交给 OutputValidator（Check.Warn.DefaultLangNoLangFile），
        // 两处判据同源，不会各写一套。
        var langRaw = Option(options, definition, "default_lang").Trim();
        var defaultLang = ComponentCatalog.ResolveUltrahandDefaultLang(langRaw, options.Language);

        // 只有「填了个东西、但那东西不是合法代码」才算损坏 —— 哨兵与空值是正常输入。
        // 判据用 IsKnownUltrahandLanguage 而不是「解析结果与原值不同」：后者会把大小写差异
        // （用户手写 ZH-CN）也算成非法，凭空报一条警告。
        var isAuto = langRaw.Length == 0
                     || string.Equals(langRaw, ComponentCatalog.AutoLanguageValue, StringComparison.OrdinalIgnoreCase);

        if (!isAuto && !ComponentCatalog.IsKnownUltrahandLanguage(langRaw))
        {
            // settings.json 是可以手改的；静默换成另一个语言的话，用户会以为改生效了
            _log.Warn(string.Format(loc["Log.InvalidDefaultLang"], langRaw, defaultLang));
        }

        ini.Comment("ultrahand", "Ultrahand 界面语言：加载 config/ultrahand/lang/<代码>.json 里对应的那一份。");
        ini.Set("ultrahand", "default_lang", defaultLang);

        // [memory] 段：可选的自定义 Overlay 内存档位。
        //
        // 语义容易误会，这里说清楚：它**不会**直接把堆改成这个大小，而是让 Ultrahand
        // 「Overlay 内存」滑条多出第 4 档（原本固定 4 / 6 / 8 MB），用户还要在
        // Ultrahand 里手动选一次。上游 source/main.cpp 的校验是「纯数字 && >8 && 偶数」，
        // 不满足就整条忽略，所以这里必须严格照抄规则，别让非法值悄悄写进去。
        var memoryRaw = Option(options, definition, "custom_overlay_memory_MB");
        var customMemoryMb = NormalizeOverlayMemory(memoryRaw);

        if (customMemoryMb is null)
        {
            if (!string.IsNullOrWhiteSpace(memoryRaw))
            {
                _log.Warn(string.Format(loc["Log.InvalidOverlayMemory"], memoryRaw));
            }
        }
        else
        {
            ini.Comment("memory", "自定义 Overlay 内存档位（MB）。Ultrahand 的 Overlay 内存滑条会多出这一档，");
            ini.Comment("memory", "需在 Ultrahand 内手动选中才生效。仅接受大于 8 的偶数。");
            ini.Set("memory", "custom_overlay_memory_MB", customMemoryMb);
        }

        // 只写 Ultrahand 自己的这份。Ultrahand 首次启动时会自动把组合键镜像到
        // /config/tesla/config.ini（源码 copyTeslaKeyComboToUltrahand），
        // 我们没必要同时维护两份，反而容易写歪。

        WriteFile(
            Path.Combine(outRoot, "config", "ultrahand", "config.ini"),
            ini.Render(),
            result,
            cancellationToken);

        // config/ovl-sysmodules/config.ini —— ovl-sysmodules overlay 自己的开关。
        //
        // 它是 Ultrahand 生态里的一个 overlay，但配置文件**独立**于 config/ultrahand/config.ini，
        // 少了这份 overlay 里那几个开关就会用内置默认值，用户在向导里选的等于白选。
        var sysmodulesOptions = definition.Options
            .Where(o => string.Equals(
                o.TargetFile,
                "config/ovl-sysmodules/config.ini",
                StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (sysmodulesOptions.Count > 0)
        {
            var sysmodules = new IniDocument();
            sysmodules.HeaderComment("; " + header);
            sysmodules.HeaderComment("; 参考：https://github.com/ppkantorski/ovl-sysmodules");

            foreach (var option in sysmodulesOptions)
            {
                sysmodules.Set(
                    option.Section ?? "ovl-sysmodules",
                    option.Key,
                    Option(options, definition, option.Key));
            }

            WriteFile(
                Path.Combine(outRoot, "config", "ovl-sysmodules", "config.ini"),
                sysmodules.Render(),
                result,
                cancellationToken);
        }
    }

    // ── payload 文件 ────────────────────────────────────────────
    /// <summary>
    /// 把暂存好的 payload 合并进 out/。
    ///
    /// payload 是**散装下载**的（Atmosphere 的 <c>fusee.bin</c>、Hekate 的
    /// <c>hekate_ctcaer_*.bin</c>），不在解压目录里，所以走单独一份暂存
    /// （<see cref="AppPaths.ComponentPayloadRoot"/>）。
    ///
    /// 落点在下载阶段就由 <c>AssetPick.Targets</c> 摆好了，暂存目录已经是「相对 out 根目录」
    /// 的结构，所以这里只做一次整棵合并，**不需要再认识任何具体文件名**。
    /// 以前是「把各组件下载目录顶层的 <c>*.bin</c> 一律平铺到 out 根目录」——
    /// 于是 fusee.bin 少了 <c>bootloader/payloads/</c> 这一层、hekate payload 也没了
    /// <c>payload.bin</c> / <c>bootloader/update.bin</c> 这两个名字。
    ///
    /// 独立于 <see cref="MergeComponentFiles"/>：两个开关各管各的，
    /// 用户可以只要 payload 不要组件本体（或反过来）。
    /// </summary>
    private void MergePayloads(
        WizardOptions options,
        string outRoot,
        ConfigGenerationResult result,
        CancellationToken cancellationToken)
    {
        foreach (var definition in ComponentCatalog.All)
        {
            if (!options.IsSelected(definition.Kind))
            {
                continue;
            }

            var staged = AppPaths.ComponentPayloadRoot(FolderName(definition.Kind));
            if (!Directory.Exists(staged))
            {
                continue;
            }

            foreach (var relative in ArchiveExtractor.MergeDirectory(staged, outRoot, cancellationToken))
            {
                // PayloadFiles 统一用 '/' 分隔：它要参与日志展示和校验器的路径比对，
                // 而 WrittenFiles 是给 File.Exists(Path.Combine(...)) 用的，两者互不影响。
                var normalized = relative.Replace('\\', '/');
                if (!result.PayloadFiles.Contains(normalized, StringComparer.OrdinalIgnoreCase))
                {
                    result.PayloadFiles.Add(normalized);
                }

                result.AddProducedFile(relative);
            }
        }

        if (result.PayloadFiles.Count > 0)
        {
            _log.Info(string.Format(
                Localization.LocalizationService.Instance["Log.PayloadsMerged"],
                string.Join(", ", result.PayloadFiles)));
        }
    }

    // ── 组件文件合并 ────────────────────────────────────────────
    /// <summary>
    /// 把各组件的解压暂存目录整棵合并进 out/。
    ///
    /// 暂存目录（<see cref="AppPaths.ComponentUnpackedRoot"/>）在下载阶段就被摆成了
    /// 「相对 out 根目录」的结构，所以这里是**无脑整棵铺开** —— 不需要认识任何具体文件，
    /// 也不会多出 <c>sdout/</c>、<c>nx-ovlloader/</c> 这类外层目录。
    /// </summary>
    private int MergeComponentFiles(
        WizardOptions options,
        string outRoot,
        ConfigGenerationResult result,
        CancellationToken cancellationToken)
    {
        var total = 0;

        foreach (var definition in ComponentCatalog.All)
        {
            if (!options.IsSelected(definition.Kind))
            {
                continue;
            }

            var folder = FolderName(definition.Kind);
            var unpacked = AppPaths.ComponentUnpackedRoot(folder);

            // 解压目录不在 = 这个组件一个文件都合并不进来。这里**不报错**（本方法只管搬运），
            // 但必须把它记成 0，让 OutputValidator 能按组件逐个对账 ——
            // 只记总数的话，「四个组件缺了一个」会被另外三个的几十个文件盖过去。
            var merged = 0;
            if (Directory.Exists(unpacked))
            {
                foreach (var relative in ArchiveExtractor.MergeDirectory(unpacked, outRoot, cancellationToken))
                {
                    // 合并进来的组件本体也要进清单，否则：
                    //   · 下次换组件 / 换版本时旧文件永远清不掉，会被一起拷进 SD 卡
                    //   · 打包后的完整性校验只覆盖配置文件，给出虚假的「全部在包内」
                    result.AddProducedFile(relative);
                    merged++;
                }
            }

            result.MergedFilesByComponent[definition.Kind] = merged;
            total += merged;
        }

        return total;
    }

    public static string FolderName(ComponentKind kind) => kind switch
    {
        ComponentKind.Atmosphere => "Atmosphere",
        ComponentKind.Hekate => "Hekate",
        ComponentKind.Ultrahand => "Ultrahand",
        ComponentKind.SysPatch => "Sys-patch",
        _ => kind.ToString(),
    };

    // ── 辅助 ────────────────────────────────────────────────────
    private static string Option(WizardOptions options, ComponentDefinition definition, string key)
    {
        var optionDefinition = definition.Options.FirstOrDefault(o => o.Key == key);
        return options.Get(definition.Kind, key, optionDefinition?.DefaultValue ?? string.Empty);
    }

    /// <summary>
    /// 校验 Ultrahand 的 <c>custom_overlay_memory_MB</c>。
    ///
    /// 规则照抄上游 <c>source/main.cpp</c>：值必须**只含数字**，且解析后
    /// <c>&gt; 8 &amp;&amp; % 2 == 0</c>；否则 Ultrahand 会整条忽略。既然写进去也没用，
    /// 这里就返回 <c>null</c> 让调用方跳过，而不是产出一份「看起来配了、其实没生效」的文件。
    /// 空串表示「不设置」，同样返回 <c>null</c>。
    /// </summary>
    private static string? NormalizeOverlayMemory(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
        {
            return null;
        }

        var text = raw.Trim();

        // 上游逐字符判断 '0'..'9'，负数、小数、正号都会让它作废
        if (!text.All(c => c is >= '0' and <= '9'))
        {
            return null;
        }

        if (!int.TryParse(text, out var megabytes))
        {
            return null;
        }

        return megabytes > 8 && megabytes % 2 == 0
            ? megabytes.ToString()
            : null;
    }

    private static string FormatTypedValue(string? prefix, string raw)
    {
        var value = raw ?? string.Empty;

        return prefix switch
        {
            "u8" => value is "1" or "true" or "True" ? "u8!0x1" : "u8!0x0",
            "u16" => "u16!" + value,
            "u32" => "u32!" + value,
            "u64" => "u64!" + value,
            "str" or "string" => "str!" + value,
            _ => value,
        };
    }

    private void WriteFile(string path, string content, ConfigGenerationResult result, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory))
        {
            AppPaths.EnsureDirectory(directory);
        }

        // ini / hosts 文件统一使用 CRLF，方便在 Windows 上直接用记事本查看
        var normalized = content.Replace("\r\n", "\n").Replace("\n", "\r\n");
        File.WriteAllText(path, normalized, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var relative = Path.GetRelativePath(AppPaths.OutputRoot, path);
        result.AddConfigFile(relative);
        _log.Info(string.Format(Localization.LocalizationService.Instance["Log.ConfigWritten"], relative));
    }

    /// <summary>删除上一次运行生成的、本次不再生成的文件。</summary>
    private void CleanPreviousOutput(string outRoot, ConfigGenerationResult result)
    {
        var manifestPath = Path.Combine(outRoot, ManifestFileName);
        if (!File.Exists(manifestPath))
        {
            return;
        }

        try
        {
            var previous = System.Text.Json.JsonSerializer.Deserialize<List<string>>(File.ReadAllText(manifestPath));
            if (previous is null)
            {
                return;
            }

            var normalizedRoot = Path.GetFullPath(outRoot);
            var emptiedParents = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var relative in previous)
            {
                var full = Path.GetFullPath(Path.Combine(outRoot, relative));
                if (!full.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase) || !File.Exists(full))
                {
                    continue;
                }

                File.Delete(full);

                var parent = Path.GetDirectoryName(full);
                if (!string.IsNullOrEmpty(parent))
                {
                    emptiedParents.Add(parent);
                }
            }

            PruneEmptyDirectories(emptiedParents, normalizedRoot);
        }
        catch (Exception ex) when (ex is IOException or System.Text.Json.JsonException or UnauthorizedAccessException)
        {
            _log.Warn("清理上一次生成的文件时出现问题：" + ex.Message);
        }
    }

    /// <summary>
    /// 删掉「因为这次清理才变空」的目录。
    ///
    /// 为什么需要：清单驱动的清理只删文件，空目录会留下来。旧版本把 sdout.zip 的内容铺到
    /// <c>out/sdout/</c>、nx-ovlloader 铺到 <c>out/nx-ovlloader/</c>，升级后文件虽然清掉了，
    /// 这两个空文件夹还杵在那儿 —— 用户看到的仍然是「多了不该有的文件夹」。
    ///
    /// 只碰**确实被清空**的那些目录，并且逐级向上直到遇到非空目录就停：
    /// 组件包里刻意带的空目录（比如 <c>switch/.packages/</c>）不在被清空的路径上，不受影响。
    /// </summary>
    private static void PruneEmptyDirectories(IEnumerable<string> candidates, string outRoot)
    {
        // 路径越长越深，从最深的开始删；删完父目录可能也空了，所以逐级向上
        foreach (var candidate in candidates.OrderByDescending(path => path.Length))
        {
            var current = candidate;

            while (!string.IsNullOrEmpty(current)
                   && !string.Equals(current, outRoot, StringComparison.OrdinalIgnoreCase)
                   && current.StartsWith(outRoot, StringComparison.OrdinalIgnoreCase)
                   && Directory.Exists(current)
                   && !Directory.EnumerateFileSystemEntries(current).Any())
            {
                Directory.Delete(current);
                current = Path.GetDirectoryName(current);
            }
        }
    }

    private void WriteManifest(string outRoot, ConfigGenerationResult result)
    {
        try
        {
            var manifestPath = Path.Combine(outRoot, ManifestFileName);
            File.WriteAllText(
                manifestPath,
                System.Text.Json.JsonSerializer.Serialize(result.WrittenFiles, new System.Text.Json.JsonSerializerOptions { WriteIndented = true }));
        }
        catch (IOException ex)
        {
            _log.Warn("写入清单文件失败：" + ex.Message);
        }
    }

    // ── 90DNS 内容 ──────────────────────────────────────────────
    private const string NinetyDnsBlock = """
# 90DNS
127.0.0.1 *nintendo.com
127.0.0.1 *nintendo.net
127.0.0.1 *nintendo.jp
127.0.0.1 *nintendo.co.jp
127.0.0.1 *nintendo.co.uk
127.0.0.1 *nintendo-europe.com
127.0.0.1 *nintendowifi.net
127.0.0.1 *nintendo.es
127.0.0.1 *nintendo.co.kr
127.0.0.1 *nintendo.tw
127.0.0.1 *nintendo.com.hk
127.0.0.1 *nintendo.com.au
127.0.0.1 *nintendo.co.nz
127.0.0.1 *nintendo.at
127.0.0.1 *nintendo.be
127.0.0.1 *nintendods.cz
127.0.0.1 *nintendo.dk
127.0.0.1 *nintendo.de
127.0.0.1 *nintendo.fi
127.0.0.1 *nintendo.fr
127.0.0.1 *nintendo.gr
127.0.0.1 *nintendo.hu
127.0.0.1 *nintendo.it
127.0.0.1 *nintendo.nl
127.0.0.1 *nintendo.no
127.0.0.1 *nintendo.pt
127.0.0.1 *nintendo.ru
127.0.0.1 *nintendo.co.za
127.0.0.1 *nintendo.se
127.0.0.1 *nintendo.ch
127.0.0.1 *nintendoswitch.com
127.0.0.1 *nintendoswitch.com.cn
127.0.0.1 *nintendoswitch.cn
207.246.121.77 *conntest.nintendowifi.net
207.246.121.77 *ctest.cdn.nintendo.net
69.25.139.140 *ctest.cdn.n.nintendoswitch.cn
95.216.149.205 *conntest.nintendowifi.net
95.216.149.205 *ctest.cdn.nintendo.net
95.216.149.205 *90dns.test
""";
}

internal sealed record BootEntry(string Title, List<string> Lines, string Caption);

/// <summary>极简 ini 构造器：支持注释、段、引导项与标题行。</summary>
internal sealed class IniDocument
{
    private readonly List<string> _header = new();
    private readonly List<Section> _sections = new();

    private sealed class Section
    {
        public Section(string name) => Name = name;

        public string Name { get; }

        public List<string> Lines { get; } = new();
    }

    public void HeaderComment(string line) => _header.Add(line);

    public void Comment(string section, string text)
        => GetSection(section).Lines.Add("; " + text);

    public void Set(string section, string key, string value)
        => GetSection(section).Lines.Add($"{key}={value}");

    public void Caption(string text) => GetSection(string.Empty).Lines.Add(text);

    public void BootEntry(string title, IEnumerable<string> lines)
    {
        var section = GetSection(title);
        section.Lines.AddRange(lines);
    }

    /// <summary>覆盖已写入的键值（用于 autoboot 索引回退）。</summary>
    public void OverrideKey(string section, string key, string value)
    {
        var target = GetSection(section);
        for (var i = 0; i < target.Lines.Count; i++)
        {
            if (target.Lines[i].StartsWith(key + "=", StringComparison.OrdinalIgnoreCase))
            {
                target.Lines[i] = $"{key}={value}";
                return;
            }
        }

        target.Lines.Add($"{key}={value}");
    }

    public string Render()
    {
        var builder = new StringBuilder();

        foreach (var line in _header)
        {
            builder.AppendLine(line);
        }

        foreach (var section in _sections)
        {
            builder.AppendLine();
            if (!string.IsNullOrEmpty(section.Name))
            {
                builder.AppendLine($"[{section.Name}]");
            }

            foreach (var line in section.Lines)
            {
                builder.AppendLine(line);
            }
        }

        return builder.ToString();
    }

    private Section GetSection(string name)
    {
        var section = _sections.FirstOrDefault(s => string.Equals(s.Name, name, StringComparison.Ordinal));
        if (section is null)
        {
            section = new Section(name);
            _sections.Add(section);
        }

        return section;
    }
}
