using System.IO;
using System.IO.Compression;
using SwitchCfwWizard.Infrastructure;

namespace SwitchCfwWizard.Services;

/// <summary>
/// 把 out/ 目录整体打包成一个 zip，方便一次性拷进 SD 卡。
///
/// 关键点：压缩包内不额外套一层目录（<c>includeBaseDirectory: false</c>），
/// 这样解压后 <c>atmosphere/</c>、<c>bootloader/</c>、<c>config/</c>、<c>exosphere.ini</c>
/// 就直接位于根目录，与 SD 卡的真实结构一一对应，用户直接把内容拖进 SD 卡即可。
/// </summary>
public static class OutputPackager
{
    private const string ArchivePrefix = "SwitchCFW-";
    private const string ArchiveExtension = ".zip";

    /// <summary>输出目录是否存在且至少有一个文件。</summary>
    public static bool HasContent(string outputRoot)
    {
        try
        {
            return Directory.Exists(outputRoot)
                   && Directory.EnumerateFiles(outputRoot, "*", SearchOption.AllDirectories).Any();
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return false;
        }
    }

    /// <summary>
    /// 打包 <paramref name="outputRoot"/> 下的全部内容。
    /// <paramref name="destinationPath"/> 为空时，自动生成
    /// <c>&lt;运行目录&gt;/SwitchCFW-yyyyMMdd-HHmmss.zip</c>。
    /// 返回最终写入的压缩包完整路径。
    /// </summary>
    public static string Create(string outputRoot, string? destinationPath = null)
    {
        if (!Directory.Exists(outputRoot))
        {
            throw new DirectoryNotFoundException(outputRoot);
        }

        if (!HasContent(outputRoot))
        {
            throw new InvalidOperationException("OUTPUT_EMPTY");
        }

        var destination = destinationPath ?? BuildDefaultPath();

        var directory = Path.GetDirectoryName(destination);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        // ZipFile.CreateFromDirectory 遇到已存在的目标文件会直接抛 IOException，先清掉。
        if (File.Exists(destination))
        {
            File.Delete(destination);
        }

        ZipFile.CreateFromDirectory(
            outputRoot,
            destination,
            CompressionLevel.Optimal,
            includeBaseDirectory: false);

        // 反复运行会在运行目录里堆下一串 7 MB 的旧压缩包，把早先那次生成的结果清掉。
        // 放在打包成功之后做：万一这次打包失败，上一次的压缩包还在，不至于两头落空。
        PruneStaleArchives(destination);

        return destination;
    }

    /// <summary>默认压缩包路径：放在运行目录下，文件名带时间戳避免互相覆盖。</summary>
    public static string BuildDefaultPath()
        => Path.Combine(AppPaths.BaseDirectory, $"{ArchivePrefix}{DateTime.Now:yyyyMMdd-HHmmss}{ArchiveExtension}");

    /// <summary>删掉同目录下早先由本工具生成的压缩包，只保留刚写出的这一个。</summary>
    private static void PruneStaleArchives(string currentArchive)
    {
        var directory = Path.GetDirectoryName(currentArchive);
        if (string.IsNullOrEmpty(directory) || !Directory.Exists(directory))
        {
            return;
        }

        var currentName = Path.GetFileName(currentArchive);

        foreach (var candidate in Directory.EnumerateFiles(directory, ArchivePrefix + "*" + ArchiveExtension))
        {
            var name = Path.GetFileName(candidate);
            if (string.Equals(name, currentName, StringComparison.OrdinalIgnoreCase)
                || !IsAutoGeneratedName(name))
            {
                continue;
            }

            try
            {
                File.Delete(candidate);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                // 被其它程序占用等原因删不掉就留着，不影响本次结果。
            }
        }
    }

    /// <summary>
    /// 严格匹配 <c>SwitchCFW-yyyyMMdd-HHmmss.zip</c>：前缀 + 8 位日期 + <c>-</c> + 6 位时间 + 后缀。
    /// 只按形状判断，这样用户自己改名保存的、或手工放进来的压缩包不会被误删。
    /// </summary>
    private static bool IsAutoGeneratedName(string fileName)
    {
        if (!fileName.StartsWith(ArchivePrefix, StringComparison.OrdinalIgnoreCase)
            || !fileName.EndsWith(ArchiveExtension, StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var stamp = fileName[ArchivePrefix.Length..^ArchiveExtension.Length];
        if (stamp.Length != 15 || stamp[8] != '-')
        {
            return false;
        }

        for (var i = 0; i < stamp.Length; i++)
        {
            if (i != 8 && !char.IsAsciiDigit(stamp[i]))
            {
                return false;
            }
        }

        return true;
    }
}
